//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountDashboard.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BudgetTimeline
    {
        [Key]
        public int Id { get; set; }
        public int MilestoneId { get; set; }
        public Nullable<System.DateTime> ActualStartDate { get; set; }
        public Nullable<System.DateTime> ActualEndDate { get; set; }
        public Nullable<int> Revenue { get; set; }
        public Nullable<int> BurntEffort { get; set; }
        public Nullable<int> UCPCPFPOrg { get; set; }
        public Nullable<int> UCPCPFPCur { get; set; }
    
        public virtual Milestone Milestone { get; set; }
    }
}
