//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountDashboard.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Quality
    {
        [Key]
        public int Id { get; set; }
        public int MileStoneId { get; set; }
        public Nullable<int> CodeReviewTotal { get; set; }
        public Nullable<int> CodeReviewClosed { get; set; }
        public Nullable<int> UTDefectsTotal { get; set; }
        public Nullable<int> UTDefectsClosed { get; set; }
        public Nullable<int> SITDefectsTotal { get; set; }
        public Nullable<int> SITDefectsClosed { get; set; }
        public Nullable<int> UATDefectsTotal { get; set; }
        public Nullable<int> UATDefectsClosed { get; set; }
        public Nullable<int> SITTestcases { get; set; }
        public Nullable<int> SITCompletion { get; set; }
        public Nullable<int> UATTestcases { get; set; }
        public Nullable<int> UATCompletion { get; set; }
        public string UTToolName { get; set; }
        public Nullable<int> UTCodeCoverage { get; set; }
    
        public virtual Milestone Milestone { get; set; }
    }
}
