//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountDashboard.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Risk
    {
        [Key]
        public int Id { get; set; }
        public int MilestoneId { get; set; }
        public Nullable<int> TotalRisk { get; set; }
        public Nullable<int> OpenRisk { get; set; }
        public string ActionPlan { get; set; }
        public string SupportRequest { get; set; }
    
        public virtual Milestone Milestone { get; set; }
    }
}
